version: '3.8'

services:
  phantom-inference:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phantom-video-gen
    ports:
      - "7860:7860"  # Gradio UI
      - "8000:8000"  # FastAPI (optional)
    volumes:
      - ./outputs:/app/outputs
      - ./uploads:/app/uploads
      - ./examples:/app/examples
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    stdin_open: true
    tty: true
